version: "3.1"

services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=chatapp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chatapp
    ports:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 api.asgi:application
    restart: always
    tty: true
    stdin_open: true
    expose:
      - 8000
      - 8001
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8